services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=apidb
  main:
    image: keter-rest:v1
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - PG_DATABASE_HOST=db
      - PG_DATABASE_PORT=5432
      - PG_DATABASE_DB=apidb
      - PG_DATABASE_USERNAME=postgres
      - PG_DATABASE_PASSWORD=postgres