services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=apidb
  main:
    image: keter-rest:v1
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - APP_PORT=3000
      - APP_LOG=keter_rest=debug,tower_http=debug,axum::rejection=debug,tower_http::trace::make_span=debug,sqlx=debug
      - APP_ROOT_USER=admin@gmail.com
      - APP_ROOT_PASSWORD=mypassword
      - PG_DATABASE_HOST=db
      - PG_DATABASE_PORT=5432
      - PG_DATABASE_DB=apidb
      - PG_DATABASE_USERNAME=postgres
      - PG_DATABASE_PASSWORD=postgres
      - JWT_SECRET=My_secret
      - JWT_EXPIRE_DURATION=3600
      - JWT_HASH_COST=4